### ISSUE TITLE
AT-Xis down. Please fix it.

### ISSUE THREAD

**Issue by rloim024** [take2560/takelab#11]
1. AT-X1,AT-X2I can't see it. Please fix it. @take2560

**Comment by rloim024** [comment]
ありがとうございます。ご苦労様でした。
Thank you very much. Thank you for all your hard work.

**Comment by take2560** [comment]
neetballは、結構不安定なのです。

**Comment by einkurogane** [comment]
うーん、それはおかしい。ジオロケーションの問題だろうか。
たしかpipe.ra1nの比べて、音が小さいだがここにneetballもう一度やってみた、送信はいいと思う。
