### ISSUE TITLE
YouTubeで晒されています。

### ISSUE THREAD

**Issue by mokemoke-club** [take2560/takelab#17]
パソコン博士TAIKIという登録者数が100万人以上いるユーチューバーの動画でプレイリストのリンクが晒されているようです。
既にお気づきになられているかもしれませんが念のためお知らせいたします。
https://youtu.be/mZU11QAjiG0

**Comment by Aoi-hosizora** [comment]
惜しいです、primehomeとdjtmewibuのは、もう２週間見られませんね。

**Comment by dm-25** [comment]
最近、見られるチャンネルも急減して寂しいです。本当の原因はなんですか？

**Comment by makimaki69** [comment]
playlistのURLがjp-primehomeになっている日本の地上、BS、CS放送を流しているチャンネルは、海外在住の日本人に向けて有料会員制で配信サービスを行っている業者（KaitekiTVなどのサービス名で）のサーバーのものです。見られなくなってしまう前までは、チャンネルへアクセスするためのURLさえわかっていれば会員ではない外部の人間が無料で動画が見れてしまう状態だったため、それを逆手にとって誰かがplaylistを作って公開していただけのことです。配慮に欠けるチャンネル登録者が多い複数のYouTuberたちがこぞって動画へのアクセス方法を大勢の日本人が見ている彼らのYouTube動画で公開してしまったため、primehomeのサーバーへ日本国内からのアクセスが急増してしまい、おかしいと思った業者側が有料会員ではない人間からのアクセスを拒否できる対策ととるようになってしまったのです。

**Comment by dm-25** [comment]
複数のyoutuberがyoutubeに公開したのが原因なんですね。こうなる事は分かっていたはずなのに何故youtuberはyoutube公開に踏み切ったのでしょうか？二度とiptvで日本のテレビは見られ無いのでしょうか？

**Comment by makimaki69** [comment]
パソコン博士TAIKIやジャッケイちゃんねるの配信動画内容や配信主のコメント等を見ましたが、彼らはjp playlistにある日本のテレビのチャンネルが有料会員向けに業者が配信しているもので、それを裏技で見れるようにしていまっているということを動画公開時点まではわかってはいなかったような感じでした。まあ、これだけ多チャンネルのテレビ放送を大々的に配信できるようにできるのは個人レベルではなくちゃんとした法人向けのサーバーからだというのはちょっと考えればわかりそうなものですが…しかもそれをタダで見れてしまうという方法はオフレコに留めておかないといけないということも…

**Comment by dm-25** [comment]
本当にその通りです。youtubeに上げれば大勢の人々が見る事は分かっていたはずのに　これをきっかけに二度と日本のiptvは見られ無くなるのでしょうか？

**Comment by makimaki69** [comment]
パソコン博士TAIKIの動画　https://youtu.be/mZU11QAjiG0　の固定コメント欄（←ここのplaylistのURLを晒している）へplaylistへの直リンクを張らない（公開しない）ように自分がコメントしておいたのですが、さっき動画へアクセスした時点では配信主からの反応はまだないですね。もちろん、直リンクは晒されたままです…　primehome以外の系統のサーバーまでアクセスできなくならないことを願うばかりです。

**Comment by dm-25** [comment]
本当に残念でなりません。全てのサーバーがアクセス出来なくならなければ良いのですが　急に見れなくなるのも辛いです
