### ISSUE TITLE
forbidden acces for some streams

### ISSUE THREAD

**Issue by joaopa00** [take2560/takelab#8]
for the stream 'http://123.30.146.172:21585/551/mpegts' I receive  mpv 'http://123.30.146.172:21585/551/mpegts'
[ffmpeg] http: HTTP error 403 Forbidden
Failed to open http://123.30.146.172:21585/551/mpegts.
[ytdl_hook] ERROR: [generic] Unable to download webpage: HTTP Error 403: Forbidden (caused by <HTTPError 403: 'Forbidden'>); please report this issue on  https://github.com/yt-dlp/yt-dlp/issues?q= , filling out the appropriate issue template. Confirm you are on the latest version using  yt-dlp -U 
[ytdl_hook] youtube-dl failed: unexpected error occurred

How do you use it?

Thanks in advance for any answer

**Comment by take2560** [comment]
It is possible that the sender's address has changed. Correct the address by deleting it.
